In [1]:
import numpy as np

In [2]:
x = np.arange(10,20,2)
print(x)
print(len(x))

[10 12 14 16 18]
5


In [3]:
x = np.arange(0,100,10)
print(x)

[ 0 10 20 30 40 50 60 70 80 90]


In [4]:
x[0:5:2]

array([ 0, 20, 40])

In [5]:
len(x)

10

In [6]:
x[-1:0:-2]

array([90, 70, 50, 30, 10])

In [7]:
x.ndim

1

In [12]:
y = np.zeros((5,8))
print(y)

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [14]:
y.ndim

2

In [15]:
y.shape

(5, 8)

In [30]:
y = 7* np.ones((5,7))
print(y)

[[ 7.  7.  7.  7.  7.  7.  7.]
 [ 7.  7.  7.  7.  7.  7.  7.]
 [ 7.  7.  7.  7.  7.  7.  7.]
 [ 7.  7.  7.  7.  7.  7.  7.]
 [ 7.  7.  7.  7.  7.  7.  7.]]


In [22]:
z = np.arange(24)
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [23]:
z.ndim

1

In [28]:
z.shape = (4,6)
print(z)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [47]:
z[1:3, 1:3] = 999
print(z)

[[  0 200   2   3   4   5]
 [111 999 999  88  88 777]
 [ 12 999 999  15  16  17]
 [ 18 200  20  21  22  23]]


In [48]:
a = np.arange(24)
a.shape = (4,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [50]:
a[a<8] = -100
print(a)

[[-100 -100 -100 -100 -100 -100]
 [-100 -100    8    9   10   11]
 [  12   13   14   15   16   17]
 [  18   19   20   21   22   23]]


In [52]:
a[a>20] = 222
print(a)

[[-100 -100 -100 -100 -100 -100]
 [-100 -100    8    9   10   11]
 [  12   13   14   15   16   17]
 [  18   19   20  222  222  222]]


In [55]:
a[(a > 10) & (a < 20)] = 1111
print(a)

[[-100 -100 -100 -100 -100 -100]
 [-100 -100    8    9   10 1111]
 [1111 1111 1111 1111 1111 1111]
 [1111 1111   20  222  222  222]]
